services:
- type: web
  name: web
  env: elixir
  repo: https://github.com/wojtekmach/phoenix_example.git
  branch: render
  buildCommand: ./build.sh
  startCommand: _build/prod/rel/phoenix_example/bin/phoenix_example start
  envVars:
  - key: ELIXIR_VERSION
    value: 1.11.2
  - key: ERLANG_VERSION
    value: 23.1.5
  - key: SECRET_KEY_BASE
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: db
      property: connectionString
  autoDeploy: false             # optional

databases:
- name: db
  ipAllowList: []
